// base class
import Core from './classes/core'

import {
  ActivatableMixin,
  AlignableCoreMixin,
  AlignableFlexElementMixin,
  AutoplayableMixin,
  BoxModelableMixin,
  ControllableCoreMixin,
  ControllableLoopMixin,
  ControllableSnapMixin,
  ControllableNudgeMixin,
  ControllableSelectMixin,
  ControllableSettleMixin,
  CssTransformableTranslateMixin,
  CssTransitionableMixin,
  DirectionableCoreMixin,
  DirectionableElementMixin,
  DraggableCoreMixin,
  DraggableMouseMixin,
  DraggableTouchMixin,
  DraggableDisableNativeDraggableBehavior,
  DraggablePreventOnEditableElementContentMixin,
  ElementableCoreMixin,
  ElementableFocusMixin,
  EventableElementMixin,
  FocusableMixin,
  IndexableCoreMixin,
  IndexableSelectNextPreviousMixin,
  ItemizableAutoRenderMixin,
  ItemizableCoreMixin,
  ItemizableElementCoreMixin,
  ItemizableSelectOnFocusedItemMixin,
  NudgeableMixin,
  RefreshableWindowResizeMixin,
  OrientationableMixin,
  OrientationableTouchActionMixin,
  TransformablePreventScrollMixin,
  VisibleContainerElementMixin,
  VisibleItemElementMixin,
  WheelableMixin,
} from './lib'

export const CarouselItem = BoxModelableMixin(
  ElementableFocusMixin(
    FocusableMixin(
      ActivatableMixin(
        VisibleItemElementMixin(
          CssTransformableTranslateMixin(
            CssTransitionableMixin(
              EventableElementMixin(ElementableCoreMixin(Core))
            )
          )
        )
      )
    )
  )
)

const Carousel = ControllableLoopMixin(
  ControllableSnapMixin(
    ControllableSelectMixin(
      ControllableSettleMixin(
        ControllableNudgeMixin(
          ControllableCoreMixin(
            RefreshableWindowResizeMixin(
              ItemizableSelectOnFocusedItemMixin(
                TransformablePreventScrollMixin(
                  AutoplayableMixin(
                    VisibleContainerElementMixin(
                      WheelableMixin(
                        DraggableDisableNativeDraggableBehavior(
                          DraggablePreventOnEditableElementContentMixin(
                            DraggableTouchMixin(
                              DraggableMouseMixin(
                                DraggableCoreMixin(
                                  IndexableSelectNextPreviousMixin(
                                    IndexableCoreMixin(
                                      AlignableFlexElementMixin(
                                        AlignableCoreMixin(
                                          DirectionableElementMixin(
                                            DirectionableCoreMixin(
                                              OrientationableTouchActionMixin(
                                                OrientationableMixin(
                                                  ItemizableAutoRenderMixin(
                                                    ItemizableElementCoreMixin(
                                                      ItemizableCoreMixin(
                                                        BoxModelableMixin(
                                                          NudgeableMixin(
                                                            EventableElementMixin(
                                                              ElementableCoreMixin(
                                                                Core
                                                              )
                                                            )
                                                          )
                                                        ),
                                                        CarouselItem
                                                      ),
                                                      CarouselItem
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)

export default Carousel
