// base class
import Core from './classes/core'

import {
  Activatable,
  AlignableCore,
  AlignableFlexElement,
  Autoplayable,
  BoxModelable,
  ControllableCore,
  ControllableLoop,
  ControllableSnap,
  ControllableNudge,
  ControllableSelect,
  ControllableSettle,
  CssTransformableTranslate,
  CssTransitionable,
  DirectionableCore,
  DirectionableElement,
  DraggableCore,
  DraggableMouse,
  DraggableTouch,
  DraggablePreventOnDraggableElement,
  DraggablePreventOnInputElement,
  ElementableCore,
  ElementableFocus,
  EventableElement,
  Focusable,
  IndexablePreviousNext,
  IndexableSelect,
  ItemizableAutoRender,
  ItemizableCore,
  ItemizableElementCore,
  ItemizableSelectOnFocusedItem,
  Nudgeable,
  RefreshableWindowResize,
  TransformablePreventScroll,
  TypeableHorizontalVertical,
  VisibleContainerElement,
  VisibleContainerItem,
  Wheelable,
} from './lib'

export const CarouselItem = BoxModelable(
  ElementableFocus(
    Focusable(
      Activatable(
        VisibleContainerItem(
          CssTransformableTranslate(
            CssTransitionable(EventableElement(ElementableCore(Core)))
          )
        )
      )
    )
  )
)

const Carousel = ControllableLoop(
  ControllableSnap(
    ControllableSelect(
      ControllableSettle(
        ControllableNudge(
          ControllableCore(
            RefreshableWindowResize(
              ItemizableSelectOnFocusedItem(
                TransformablePreventScroll(
                  Autoplayable(
                    VisibleContainerElement(
                      Wheelable(
                        DraggablePreventOnDraggableElement(
                          DraggablePreventOnInputElement(
                            DraggableTouch(
                              DraggableMouse(
                                DraggableCore(
                                  IndexablePreviousNext(
                                    IndexableSelect(
                                      AlignableFlexElement(
                                        AlignableCore(
                                          DirectionableElement(
                                            DirectionableCore(
                                              TypeableHorizontalVertical(
                                                ItemizableAutoRender(
                                                  ItemizableElementCore(
                                                    ItemizableCore(
                                                      BoxModelable(
                                                        Nudgeable(
                                                          EventableElement(
                                                            ElementableCore(
                                                              Core
                                                            )
                                                          )
                                                        )
                                                      ),
                                                      CarouselItem
                                                    ),
                                                    CarouselItem
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)

export default Carousel
