// base class
import Core from './classes/core'

import {
  ActivatableMixin,
  AlignableCoreMixin,
  AlignableFlexElementMixin,
  AutoplayableMixin,
  BoxModelableMixin,
  ControllableCoreMixin,
  ControllableLoopMixin,
  ControllableSnapMixin,
  ControllableNudgeMixin,
  ControllableSelectMixin,
  ControllableSettleMixin,
  CssTransformableTranslateMixin,
  CssTransitionableMixin,
  DirectionableCoreMixin,
  DirectionableElementMixin,
  DraggableCoreMixin,
  DraggableMouseMixin,
  DraggableTouchMixin,
  DraggablePreventOnDraggableElementMixin,
  DraggablePreventOnInputElementMixin,
  ElementableCoreMixin,
  ElementableFocusMixin,
  EventableElementMixin,
  FocusableMixin,
  IndexablePreviousNextMixin,
  IndexableSelectMixin,
  ItemizableAutoRenderMixin,
  ItemizableCoreMixin,
  ItemizableElementCoreMixin,
  ItemizableSelectOnFocusedItemMixin,
  NudgeableMixin,
  RefreshableWindowResizeMixin,
  TransformablePreventScrollMixin,
  TypeableHorizontalVerticalMixin,
  VisibleContainerElementMixin,
  VisibleContainerItemMixin,
  WheelableMixin,
} from './lib'

export const CarouselItem = BoxModelableMixin(
  ElementableFocusMixin(
    FocusableMixin(
      ActivatableMixin(
        VisibleContainerItemMixin(
          CssTransformableTranslateMixin(
            CssTransitionableMixin(
              EventableElementMixin(ElementableCoreMixin(Core))
            )
          )
        )
      )
    )
  )
)

const Carousel = ControllableLoopMixin(
  ControllableSnapMixin(
    ControllableSelectMixin(
      ControllableSettleMixin(
        ControllableNudgeMixin(
          ControllableCoreMixin(
            RefreshableWindowResizeMixin(
              ItemizableSelectOnFocusedItemMixin(
                TransformablePreventScrollMixin(
                  AutoplayableMixin(
                    VisibleContainerElementMixin(
                      WheelableMixin(
                        DraggablePreventOnDraggableElementMixin(
                          DraggablePreventOnInputElementMixin(
                            DraggableTouchMixin(
                              DraggableMouseMixin(
                                DraggableCoreMixin(
                                  IndexablePreviousNextMixin(
                                    IndexableSelectMixin(
                                      AlignableFlexElementMixin(
                                        AlignableCoreMixin(
                                          DirectionableElementMixin(
                                            DirectionableCoreMixin(
                                              TypeableHorizontalVerticalMixin(
                                                ItemizableAutoRenderMixin(
                                                  ItemizableElementCoreMixin(
                                                    ItemizableCoreMixin(
                                                      BoxModelableMixin(
                                                        NudgeableMixin(
                                                          EventableElementMixin(
                                                            ElementableCoreMixin(
                                                              Core
                                                            )
                                                          )
                                                        )
                                                      ),
                                                      CarouselItem
                                                    ),
                                                    CarouselItem
                                                  )
                                                )
                                              )
                                            )
                                          )
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)

export default Carousel
